// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB02mHAR5bSxkmweQ6ZGWMWj0iyXsg-Mo0',
    appId: '1:730592388989:web:be43f0428545a5fcb70e14',
    messagingSenderId: '730592388989',
    projectId: 'mobifix-3b8af',
    authDomain: 'mobifix-3b8af.firebaseapp.com',
    storageBucket: 'mobifix-3b8af.appspot.com',
    measurementId: 'G-9M0RPZWR7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGpEjzGUHNd7QtfktIrkMhs5qtx4R-_Bo',
    appId: '1:730592388989:android:bc201f2fb4f94f71b70e14',
    messagingSenderId: '730592388989',
    projectId: 'mobifix-3b8af',
    storageBucket: 'mobifix-3b8af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeRI3c8CVi303D4qOH3tCye_e4HjvFg5Y',
    appId: '1:730592388989:ios:3378dd60f036c4fab70e14',
    messagingSenderId: '730592388989',
    projectId: 'mobifix-3b8af',
    storageBucket: 'mobifix-3b8af.appspot.com',
    iosBundleId: 'com.example.mobifix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeRI3c8CVi303D4qOH3tCye_e4HjvFg5Y',
    appId: '1:730592388989:ios:3378dd60f036c4fab70e14',
    messagingSenderId: '730592388989',
    projectId: 'mobifix-3b8af',
    storageBucket: 'mobifix-3b8af.appspot.com',
    iosBundleId: 'com.example.mobifix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB02mHAR5bSxkmweQ6ZGWMWj0iyXsg-Mo0',
    appId: '1:730592388989:web:6ee3bafec1fad8b3b70e14',
    messagingSenderId: '730592388989',
    projectId: 'mobifix-3b8af',
    authDomain: 'mobifix-3b8af.firebaseapp.com',
    storageBucket: 'mobifix-3b8af.appspot.com',
    measurementId: 'G-HTSV6ZKESN',
  );
}
